source 'https://gem.coop'

gem 'rails', '~> 8.1.2'
gem 'propshaft'
gem 'sqlite3', '>= 2.1'
gem 'puma', '>= 7.0'
gem 'ros-apartment', require: 'apartment'
gem 'rotp', '~> 6.3'
gem 'pagy', '~> 43.3'

group :development, :test do
  gem 'debug', platforms: %i[ mri ], require: 'debug/prelude'
  # gem 'rails_live_reload'
  gem 'hotwire-livereload'
end
