source 'https://gem.coop'


gem 'json', '~> 2.9'
gem 'pagy', '~> 43.6'
gem 'propshaft'
gem 'puma', '~> 8.0'
gem 'rails', '~> 8.1'
gem 'ros-apartment', '~> 3.4', require: 'apartment'
gem 'rotp', '~> 6.3'
gem 'rubyzip', '~> 3.6'
gem 'solid_cable', '~> 4.0'
gem 'solid_cache', '~> 1.0'
gem 'solid_queue', '~> 1.7'
gem 'sqlite3', '~> 2.9'
gem 'stimulus-rails', '~> 1.3'
gem 'turbo-rails', '~> 2.0'

group :development, :test do
  gem 'debug', platforms: %i[ mri ], require: 'debug/prelude'
  gem 'hotwire-livereload', '~> 2.1'
end
